{% set version = '0.0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xicra.stats
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/HCGB-IGTP/XICRA.stats
  git_tag: v1.1

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-scales
    - r-tidyr

  run:
    - r-base
    - r-scales
    - r-tidyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('XICRA.stats')"           # [not win]
    - "\"%R%\" -e \"library('XICRA.stats')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/HCGB-IGTP/XICRA.stats

  license: use_gpl3_license()
  summary: Parses and generates statistics for the XICRA small RNA pipeline (add website link)

  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: XICRA.stats
# Title: Parses and creates statistics for XICRA analysis
# Version: 0.0.1
# Authors@R: person(given = "Jose Francisco", family = "Sanchez-Herrero", role = c("aut", "cre"), email = "jfbioinformatics@gmail.com")
# Description: Parses and generates statistics for the XICRA small RNA pipeline (add website link)
# License: use_gpl3_license()
# Encoding: UTF-8
# LazyData: true
# Roxygen: list(markdown = TRUE)
# RoxygenNote: 7.1.2.9000
# Depends: tidyr, scales
# URL: https://github.com/HCGB-IGTP/XICRA.stats

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
